from pathlib import Path
import jax
import jax.numpy as jnp
import numpy as np
import matplotlib.pyplot as plt
import wandb
from matplotlib.animation import PillowWriter
from matplotlib.transforms import ScaledTranslation

from mosaic.common import TOKENS

# ============================================================================
# Helper functions
# ============================================================================

def _group_losses(losses: dict) -> dict[str, list[tuple[str, np.ndarray]]]:
    groups = {}
    for full_name, values in losses.items():
        if ".losses." in full_name:
            prefix, loss_name = full_name.split(".losses.", 1)
        elif "other_losses" in full_name:
            prefix, loss_name = full_name.split(".", 1)
        else:
            prefix, loss_name = "", full_name
        if prefix not in groups:
            groups[prefix] = [(loss_name, values)]
        else:
            groups[prefix].append((loss_name, values))
    return groups

def plot_losses(loss: np.ndarray, additional_losses: dict[np.ndarray] | None = None):
    steps = range(len(loss))

    handles, labels = [], []
    legend_lines = 1
    groups = {}
    # divide losses by source (model losses / other losses)
    if additional_losses is not None:
        groups = _group_losses(additional_losses)
        legend_lines += sum(len(g) + (1 if p else 0) for p, g in groups.items())

    all_names = [n for g in groups.values() for n, _ in g]
    max_name_len = max((len(n) for n in all_names))
    legend_width = (max_name_len + 30) * 0.065 + 0.5
    fig_h = max(4, legend_lines * 0.35)
    fig, ax = plt.subplots(figsize=(10 + legend_width, fig_h))

    best_loss, last_loss = float(np.min(loss)), float(loss[-1])
    line, = ax.plot(steps, loss, color="black", linewidth=2.0)
    handles.append(line)
    labels.append(f"Total Loss (best={best_loss:.2f}, last={last_loss:.2f})")

    blank = plt.Line2D([], [], linestyle="none", marker="none")
    header_indices = set()

    for prefix, group in groups.items():
        if prefix:
            header_indices.add(len(handles))
            handles.append(blank)
            labels.append(prefix)
        for name, values in group:
            if values.ndim == 2:
                values = np.mean(values, axis=-1)
            if values.mean() < 0:
                values = -values
                name = f"(neg) {name}"
            best_val, last_val = float(np.min(values)), float(values[-1])
            line, = ax.plot(steps, values, alpha=0.35, linewidth=1.2)
            handles.append(line)
            labels.append(f"  {name} (best={best_val:.2f}, last={last_val:.2f})")

    ax.set_xlabel("step")
    ax.set_ylabel("loss")
    ax.set_xlim(0, len(loss) - 1)
    leg = ax.legend(handles, labels, loc="upper left", bbox_to_anchor=(1.02, 1), fontsize=8)
    offset = ScaledTranslation(-25 / 72, 0, fig.dpi_scale_trans)
    for i in header_indices:
        text = leg.get_texts()[i]
        text.set_transform(text.get_transform() + offset)
    fig.tight_layout()
    return fig

def plot_pssm_heatmap(pssm, ax=None, return_wandb_image: bool = False):
    seq_len = pssm.shape[0]
    aa_labels = list(TOKENS)
    if ax is None:
        fig, ax = plt.subplots(1, 1, figsize=(4, 12))
    else:
        fig = ax.figure
        ax.clear()

    ax.imshow(pssm, aspect="auto", cmap='Greys', vmin=0, vmax=1)
    ax.set_title("PSSM")
    ax.set_xticks(np.arange(len(aa_labels)))
    ax.set_xticklabels(aa_labels)
    ax.set_yticks(np.arange(0, seq_len, 10))
    fig.tight_layout()

    if return_wandb_image:
        wandb_image = wandb.Image(fig)
        plt.close(fig)
        return wandb_image
    return fig

def make_pssm_video(pssm_trajectory, output_path: str = "pssm_trajectory.gif", fps: int = 10):
    n_steps = pssm_trajectory.shape[0]
    fig, ax = plt.subplots(1, 1, figsize=(4, 12))
    writer = PillowWriter(fps=fps)
    with writer.saving(fig, output_path, dpi=100):
        for i in range(n_steps):
            plot_pssm_heatmap(pssm_trajectory[i], ax=ax)
            ax.set_title(f"PSSM — step {i} / {n_steps - 1}")
            writer.grab_frame()
    plt.close(fig)
    return output_path

# ============================================================================
# Logger class
# ============================================================================

def _default_is_leaf(x):
    """A list of non-dict items is treated as a trajectory leaf (not traversed further)."""
    return isinstance(x, list) and len(x) > 0 and not isinstance(x[0], dict)

def _nan_like(value):
    if isinstance(value, np.ndarray):
        return np.full_like(value, np.nan)
    return np.nan

def _align_trees(tree_a, tree_b, fill_a_fn, fill_b_fn, is_leaf=None):
    """Align two nested dicts so they have identical key structure.

    For any key present in one tree but not the other, insert a placeholder
    generated by the corresponding fill function applied to the existing value.
    """
    if is_leaf is not None and (is_leaf(tree_a) or is_leaf(tree_b)):
        return tree_a, tree_b
    if not isinstance(tree_a, dict) or not isinstance(tree_b, dict):
        return tree_a, tree_b

    all_keys = set(tree_a) | set(tree_b)
    aligned_a, aligned_b = {}, {}
    for k in all_keys:
        # if key in both trees recurse deeper
        if k in tree_a and k in tree_b:
            a_child, b_child = _align_trees(
                tree_a[k], tree_b[k], fill_a_fn, fill_b_fn, is_leaf
            )
            aligned_a[k] = a_child
            aligned_b[k] = b_child
        # otherwise fill in the missing entry in the correct tree
        elif k in tree_a:
            aligned_a[k] = tree_a[k]
            aligned_b[k] = jax.tree.map(fill_b_fn, tree_a[k], is_leaf=is_leaf)
        else:
            aligned_a[k] = jax.tree.map(fill_a_fn, tree_b[k], is_leaf=is_leaf)
            aligned_b[k] = tree_b[k]
    return aligned_a, aligned_b

class TrajectoryLogger:
    def __init__(self, is_leaf=None):
        self.trajectory_list = None
        self.trajectory = None
        self.is_leaf = is_leaf if is_leaf is not None else _default_is_leaf

    def update(self, aux):
        to_cpu = lambda x: np.array(x) if isinstance(x, (jax.Array, jnp.ndarray)) else x

        # Initialize
        if self.trajectory_list is None:
            self.trajectory_list = jax.tree.map(lambda x: [to_cpu(x)], aux)
        # Update
        else:
            n = len(self)
            traj, aux_aligned = _align_trees(
                self.trajectory_list,
                aux,
                fill_a_fn=lambda v: [_nan_like(to_cpu(v))] * n,
                fill_b_fn=lambda v: _nan_like(v[0]) if isinstance(v, list) and len(v) > 0 else np.nan,
                is_leaf=self.is_leaf,
            )
            self.trajectory_list = jax.tree.map(
                lambda traj_leaf, new_value: traj_leaf + [to_cpu(new_value)],
                traj,
                aux_aligned,
                is_leaf=self.is_leaf,
            )

    def __len__(self):
        if self.trajectory_list is not None:
            return len(self.trajectory_list["optim"]["pssm"])
        elif self.trajectory is not None:
            return len(self.trajectory["optim"]["pssm"])
        return len(self.traj)

    def __add__(self, other):
        merged = TrajectoryLogger(is_leaf=self.is_leaf)
        # Merge based on trajectory_list if available (faster)
        if self.trajectory_list is not None and other.trajectory_list is not None:
            n_self = len(self)
            n_other = len(other)
            a, b = _align_trees(
                self.trajectory_list,
                other.trajectory_list,
                fill_a_fn=lambda v: [_nan_like(v[0])] * n_self if isinstance(v, list) and len(v) > 0 else [np.nan] * n_self,
                fill_b_fn=lambda v: [_nan_like(v[0])] * n_other if isinstance(v, list) and len(v) > 0 else [np.nan] * n_other,
                is_leaf=self.is_leaf,
            )
            merged.trajectory_list = jax.tree.map(
                lambda x, y: x + y,
                a, b,
                is_leaf=self.is_leaf,
            )
        # Fall back to trajectory (slower), useful for loaded trajectories
        elif self.trajectory is not None and other.trajectory is not None:
            n_self = self.trajectory["optim"]["pssm"].shape[0]
            n_other = other.trajectory["optim"]["pssm"].shape[0]
            a, b = _align_trees(
                self.trajectory,
                other.trajectory,
                fill_a_fn=lambda v: np.full((n_self, *v.shape[1:]), np.nan) if isinstance(v, np.ndarray) else v,
                fill_b_fn=lambda v: np.full((n_other, *v.shape[1:]), np.nan) if isinstance(v, np.ndarray) else v,
            )
            merged.trajectory = jax.tree.map(
                lambda x, y: np.concatenate([x, y], axis=0) if isinstance(x, np.ndarray) else x,
                a, b,
            )
        else:
            raise RuntimeError(
                    "Both loggers must have trajectory_list or trajectory to be added."
                    "Call clean_trajectory() on each first, or ensure trajectory_list is available."
                )
        return merged

    def __getitem__(self, idx):
        sliced = TrajectoryLogger(is_leaf=self.is_leaf)
        if self.trajectory_list is not None:
            sliced.trajectory_list = jax.tree.map(
                lambda lst: lst[idx],
                self.trajectory_list,
                is_leaf=self.is_leaf,
            )

        if self.trajectory is not None:
            def _slice(x):
                if isinstance(x, np.ndarray):
                    return x[idx]
                return x
            sliced.trajectory = jax.tree.map(_slice, self.trajectory)

        if sliced.trajectory_list is None and sliced.trajectory is None:
            raise RuntimeError("Logger has neither trajectory_list nor trajectory to slice.")

        return sliced

    def clean_trajectory(self, keep_trajectory_list=False):
        if self.trajectory_list is None:
            raise RuntimeError(
                "Logger does not have trajectory_list to be cleaned."
                "If logger was loaded from file, it already has a trajectory."
            )
        # Stack arrays where shape is constant across steps
        def _stack(lst):
            try:
                return np.stack(lst)
            except (ValueError, TypeError):
                return lst
        stacked = jax.tree_util.tree_map(_stack, self.trajectory_list, is_leaf=self.is_leaf)
        self.trajectory = stacked

        # Optionally clean memory
        if not keep_trajectory_list:
            self.trajectory_list = None

        return self.trajectory

    def to_flat_dict(self, sep: str = "."):
        if self.trajectory is None:
            self.clean_trajectory()

        flat = {}
        for path, leaf in jax.tree_util.tree_leaves_with_path(self.trajectory):
            parts = [str(p.key) for p in path if hasattr(p, "key")]
            path_str = sep.join(parts) if parts else "value"
            flat[path_str] = leaf
        return flat

    @classmethod
    def load(cls, path: str):
        import pickle
        logger = cls()
        with open(path, "rb") as f:
            logger.trajectory = pickle.load(f)
        return logger

    def save(self, log_path: Path, save_loss_plot: bool = True, save_pssm_video: bool = True):
        import pickle

        log_path = Path(log_path)
        if not log_path.exists():
           log_path.mkdir(parents=True, exist_ok=True)

        if self.trajectory is None:
            self.clean_trajectory()

        # Save final sequence
        final_pssm = self.trajectory["optim"]["pssm"][-1]
        final_idxs = np.array(jnp.argmax(final_pssm, axis=-1))
        tokens_arr = np.array(list(TOKENS))
        final_sequence = "".join(tokens_arr[final_idxs])
        (log_path / "sequence.txt").write_text(final_sequence)

        # Save trajectory
        (log_path / "trajectory.pkl").write_bytes(pickle.dumps(self.trajectory))

        # Save plot of losses
        if save_loss_plot:
            flat = self.to_flat_dict()
            losses_dict = {k: v for k,v in flat.items() if "losses" in k}
            fig = plot_losses(
                loss=self.trajectory["optim"]["loss"],
                additional_losses=losses_dict,
            )
            fig.savefig(log_path / "losses.png")
            plt.close(fig)

        # Save pssm evolution video
        if save_pssm_video:
            make_pssm_video(
                self.trajectory["optim"]["pssm"],
                output_path=log_path / "pssm_evolution.gif",
            )

        print(f"Saved logs to: {log_path}")

# ============================================================================
# wandb logging
# ============================================================================

def aux_to_wandb(aux):
    log = {}
    for path, leaf in jax.tree_util.tree_leaves_with_path(aux):
        parts = [str(p.key) for p in path if hasattr(p, "key")]
        path_str = ".".join(parts) if parts else "value"
        if "losses" in path_str and isinstance(leaf, (np.ndarray, jnp.ndarray)):
            log[path_str] = float(np.mean(leaf))
        elif "pssm" in path_str:
            log[path_str] = plot_pssm_heatmap(leaf, return_wandb_image=True)
        elif isinstance(leaf, (float, int)) or (hasattr(leaf, "ndim") and leaf.ndim == 0):
            log[path_str] = float(leaf)
    return log